/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.WebServiceCep;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author John Victor
 */
public class FormCategoria extends javax.swing.JInternalFrame {

    boolean mensagemSucesso = false;
    String mensagem = "";
    private String cep;

    FormMenu telaPai = null;

    /**
     * Creates new form Home
     */
    public FormCategoria(FormMenu telaPai) {

        initComponents();
        
        this.telaPai = telaPai;

        txtdescricao.setText("Descrição");
        lblDescricao.setVisible(false);

        campoMensagem.setVisible(false);
        lblMensagem.setVisible(false);

    }

    public void limpar() {

        txtdescricao.setText("Login");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    FormHome home;

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpTitulo = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btncancelar = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnConfirmar = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtdescricao = new javax.swing.JFormattedTextField();
        lblDescricao = new java.awt.Label();
        jpTitulo1 = new javax.swing.JPanel();
        lblTituloForm4 = new javax.swing.JLabel();
        lblTituloForm5 = new javax.swing.JLabel();
        campoMensagem = new javax.swing.JPanel();
        lblMensagem = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 0));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        setMinimumSize(new java.awt.Dimension(300, 80));
        setPreferredSize(new java.awt.Dimension(1210, 640));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpTitulo.setBackground(new java.awt.Color(255, 255, 255));
        jpTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btncancelar.setBackground(new java.awt.Color(109, 127, 145));
        btncancelar.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btncancelar.setForeground(new java.awt.Color(255, 255, 255));
        btncancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btncancelar.setText("CANCELAR");
        btncancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncancelarMouseClicked(evt);
            }
        });
        jPanel3.add(btncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 60));

        jpTitulo.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 60));

        jPanel4.setBackground(new java.awt.Color(109, 127, 145));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnConfirmar.setBackground(new java.awt.Color(109, 127, 145));
        btnConfirmar.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnConfirmar.setText("CONFIRMAR");
        btnConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfirmarMouseClicked(evt);
            }
        });
        jPanel4.add(btnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 60));

        jpTitulo.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 220, 60));

        jPanel1.add(jpTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 560, 780, 60));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, -1, -1));

        txtdescricao.setForeground(new java.awt.Color(109, 127, 145));
        txtdescricao.setText("Descrição");
        txtdescricao.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtdescricao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtdescricaoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtdescricaoFocusLost(evt);
            }
        });
        txtdescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdescricaoActionPerformed(evt);
            }
        });
        jPanel1.add(txtdescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 780, 40));

        lblDescricao.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblDescricao.setForeground(new java.awt.Color(109, 127, 145));
        lblDescricao.setText("Descrição");
        jPanel1.add(lblDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 70, 20));

        jpTitulo1.setBackground(new java.awt.Color(109, 127, 145));
        jpTitulo1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloForm4.setBackground(new java.awt.Color(109, 127, 145));
        lblTituloForm4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblTituloForm4.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloForm4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloForm4.setText("FORMULARIO DA CATEGORIA");
        jpTitulo1.add(lblTituloForm4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 60));

        jPanel1.add(jpTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 780, 60));

        lblTituloForm5.setBackground(new java.awt.Color(109, 127, 145));
        lblTituloForm5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblTituloForm5.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloForm5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloForm5.setText("FORMULARIO DO CLIENTE");
        jPanel1.add(lblTituloForm5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 770, 60));

        campoMensagem.setBackground(new java.awt.Color(255, 204, 204));
        campoMensagem.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMensagem.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblMensagem.setForeground(new java.awt.Color(255, 51, 51));
        lblMensagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMensagem.setText("You have an error in you form");
        campoMensagem.add(lblMensagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 5, 750, 30));

        jPanel1.add(campoMensagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 780, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1230, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtdescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdescricaoActionPerformed

    private void btnConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmarMouseClicked

        if (txtdescricao.getText().equals("Descrição") || txtdescricao.getText().trim().isEmpty()) {
            mensagem = "Descrição da categoria não pode ser vazia";
            mensagemSucesso = false;
            txtdescricao.grabFocus();

        } else {
            mensagemSucesso = true;
        }
        if (mensagemSucesso) {

            JOptionPane.showMessageDialog(null, "vai malandra");

        } else {

            campoMensagem.setBackground(new Color(255, 204, 204));
            campoMensagem.setVisible(true);
            lblMensagem.setText(mensagem);
            lblMensagem.setVisible(true);
            lblMensagem.setForeground(new Color(204, 0, 0));
        }
    }//GEN-LAST:event_btnConfirmarMouseClicked

    private void txtdescricaoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdescricaoFocusGained
        // TODO add your handling code here:

        if (txtdescricao.getText().equals("Login")) {
            txtdescricao.setText("");
            lblDescricao.setVisible(true);
        }

    }//GEN-LAST:event_txtdescricaoFocusGained

    private void txtdescricaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdescricaoFocusLost
        // TODO add your handling code here:
        if (txtdescricao.getText().isEmpty()) {
            txtdescricao.setText("Login");
            lblDescricao.setVisible(false);
        }

    }//GEN-LAST:event_txtdescricaoFocusLost

    private void btncancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncancelarMouseClicked
        // TODO add your handling code here:
        dispose();

        home = new FormHome();
        this.telaPai.Internal(home);
    }//GEN-LAST:event_btncancelarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnConfirmar;
    private javax.swing.JLabel btncancelar;
    private javax.swing.JPanel campoMensagem;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jpTitulo;
    private javax.swing.JPanel jpTitulo1;
    private java.awt.Label lblDescricao;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JLabel lblTituloForm4;
    private javax.swing.JLabel lblTituloForm5;
    private javax.swing.JFormattedTextField txtdescricao;
    // End of variables declaration//GEN-END:variables
}
