/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author John Victor
 */
public class FormLogin extends javax.swing.JFrame {

    /**
     * Creates new form FormLogin
     */
    public FormLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpTitulo = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblemail = new java.awt.Label();
        lblcpf = new java.awt.Label();
        campoMensagem = new javax.swing.JPanel();
        lblMensagem = new javax.swing.JLabel();
        jpTitulo1 = new javax.swing.JPanel();
        lblTituloForm4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btncancelar = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnProsseguir = new javax.swing.JLabel();
        txtemail1 = new javax.swing.JTextField();
        txtsenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(860, 500));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpTitulo.setBackground(new java.awt.Color(255, 255, 255));
        jpTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jpTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 560, 780, 60));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, -1, -1));

        lblemail.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblemail.setForeground(new java.awt.Color(109, 127, 145));
        lblemail.setText("Email");
        jPanel1.add(lblemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 440, 20));

        lblcpf.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblcpf.setForeground(new java.awt.Color(109, 127, 145));
        lblcpf.setText("Senha");
        jPanel1.add(lblcpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 370, 20));

        campoMensagem.setBackground(new java.awt.Color(255, 204, 204));
        campoMensagem.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMensagem.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblMensagem.setForeground(new java.awt.Color(255, 51, 51));
        lblMensagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMensagem.setText("You have an error in you form");
        campoMensagem.add(lblMensagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 5, 780, 30));

        jPanel1.add(campoMensagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 780, 40));

        jpTitulo1.setBackground(new java.awt.Color(109, 127, 145));
        jpTitulo1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloForm4.setBackground(new java.awt.Color(109, 127, 145));
        lblTituloForm4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblTituloForm4.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloForm4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloForm4.setText("LOCAVHS");
        jpTitulo1.add(lblTituloForm4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 60));

        jPanel1.add(jpTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 780, 60));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel2.setText("Login");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 110, -1));

        jPanel3.setBackground(new java.awt.Color(255, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btncancelar.setBackground(new java.awt.Color(109, 127, 145));
        btncancelar.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btncancelar.setForeground(new java.awt.Color(255, 255, 255));
        btncancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btncancelar.setText("CANCELAR");
        btncancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncancelarMouseClicked(evt);
            }
        });
        jPanel3.add(btncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 210, 60));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, 60));

        jPanel4.setBackground(new java.awt.Color(109, 127, 145));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnProsseguir.setBackground(new java.awt.Color(109, 127, 145));
        btnProsseguir.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnProsseguir.setForeground(new java.awt.Color(255, 255, 255));
        btnProsseguir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnProsseguir.setText("Prosseguir");
        btnProsseguir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProsseguirMouseClicked(evt);
            }
        });
        jPanel4.add(btnProsseguir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 210, 60));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 350, -1, 60));

        txtemail1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtemail1.setForeground(new java.awt.Color(109, 127, 145));
        txtemail1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtemail1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtemail1FocusLost(evt);
            }
        });
        txtemail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemail1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtemail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 780, 40));

        txtsenha.setForeground(new java.awt.Color(109, 127, 145));
        txtsenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtsenhaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtsenhaFocusLost(evt);
            }
        });
        jPanel1.add(txtsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 780, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncancelarMouseClicked
        // TODO add your handling code here:
        dispose();

        home = new FormHome();
        this.telaPai.Internal(home);
    }//GEN-LAST:event_btncancelarMouseClicked

    private void btnProsseguirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProsseguirMouseClicked
        // TODO add your handling code here:

        campoMensagem.setVisible(false);
        lblMensagem.setVisible(false);
        mensagem = "";

        validaEmail(txtemail.getText());

        validaCPF(txtcpf.getText());

        if (!stateemail) {
            mensagem = " O email digitado é invalido";
            mensagemSucesso = false;
            txtemail.grabFocus();

        } else if (!stateCPF) {

            mensagem = "O CPF digitado é Invalido";
            mensagemSucesso = false;
            txtcpf.grabFocus();

        } else if (txtrg.getText().trim().isEmpty() || txtrg.getText().equals("  -   -   - ")) {

            mensagem = "RG não pode ser vazio";
            mensagemSucesso = false;
            txtrg.grabFocus();
        } else if (txttelefone.getText().trim().isEmpty() || txttelefone.getText().equals("(  )       -    ")) {

            mensagem = "Telefone não pode ser vazio";
            mensagemSucesso = false;
            txttelefone.grabFocus();
        }
        else{
            mensagemSucesso = true;
        }

        if (mensagemSucesso) {

            clientePasso3 = new FormClientePasso3(this.telaPai);
            this.telaPai.Internal(clientePasso3);
        } else {

            campoMensagem.setBackground(new Color(255, 204, 204));
            campoMensagem.setVisible(true);
            lblMensagem.setText(mensagem);
            lblMensagem.setVisible(true);
        }
    }//GEN-LAST:event_btnProsseguirMouseClicked

    private void txtemail1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtemail1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemail1FocusGained

    private void txtemail1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtemail1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemail1FocusLost

    private void txtemail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemail1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemail1ActionPerformed

    private void txtsenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtsenhaFocusGained
        // TODO add your handling code here:

        String senha = new String(txtsenha.getPassword());

        if (senha.equals("**********")) {
            txtsenha.setText("");
        }
    }//GEN-LAST:event_txtsenhaFocusGained

    private void txtsenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtsenhaFocusLost
        // TODO add your handling code here:
        String senha = new String(txtsenha.getPassword());
        if (senha.equals("")) {
            txtsenha.setText("**********");
        }
    }//GEN-LAST:event_txtsenhaFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnProsseguir;
    private javax.swing.JLabel btncancelar;
    private javax.swing.JPanel campoMensagem;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jpTitulo;
    private javax.swing.JPanel jpTitulo1;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JLabel lblTituloForm4;
    private java.awt.Label lblcpf;
    private java.awt.Label lblemail;
    private javax.swing.JTextField txtemail1;
    private javax.swing.JPasswordField txtsenha;
    // End of variables declaration//GEN-END:variables
}
