/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Dimension;
import View.FormClientePasso2;
import View.FormMenu;
import java.awt.Color;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author John Victor
 */
public class FormFilmePasso2 extends javax.swing.JInternalFrame {

    boolean mensagemSucesso = false;
    String mensagem = "";

    FormMenu telaPai = null;

    /**
     * Creates new form Home
     */
    public FormFilmePasso2(FormMenu telaPai) {
        initComponents();
        this.telaPai = telaPai;

        txtClassEtaria.setText("Nome");
        lblDiretor.setVisible(false);
        txtSinopse.setText("Sobrenome");
        lblSobrenome.setVisible(false);
        campoMensagem.setVisible(false);
        lblMensagem.setVisible(false);

    }

    FormClientePasso2 clientePasso2;
    FormHome home;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpSexo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jpTitulo = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btncancelar = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnProsseguir = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnpasso01 = new javax.swing.JPanel();
        lblpasso01 = new javax.swing.JLabel();
        pnpasso02 = new javax.swing.JPanel();
        lblpasso02 = new javax.swing.JLabel();
        pnpasso03 = new javax.swing.JPanel();
        lblpasso03 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblDatanasc = new java.awt.Label();
        jpTitulo1 = new javax.swing.JPanel();
        lblTituloForm4 = new javax.swing.JLabel();
        lblDiretor = new java.awt.Label();
        lblSobrenome = new java.awt.Label();
        campoMensagem = new javax.swing.JPanel();
        lblMensagem = new javax.swing.JLabel();
        txtClassEtaria = new javax.swing.JTextField();
        lblStatus = new java.awt.Label();
        intCopias = new javax.swing.JTextField();
        txtDuracao = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextSinopse = new javax.swing.JTextArea();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        setMinimumSize(new java.awt.Dimension(300, 80));
        setPreferredSize(new java.awt.Dimension(1210, 640));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpTitulo.setBackground(new java.awt.Color(255, 255, 255));
        jpTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btncancelar.setBackground(new java.awt.Color(109, 127, 145));
        btncancelar.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btncancelar.setForeground(new java.awt.Color(255, 255, 255));
        btncancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btncancelar.setText("CANCELAR");
        btncancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncancelarMouseClicked(evt);
            }
        });
        jPanel3.add(btncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 60));

        jpTitulo.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 60));

        jPanel4.setBackground(new java.awt.Color(109, 127, 145));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnProsseguir.setBackground(new java.awt.Color(109, 127, 145));
        btnProsseguir.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnProsseguir.setForeground(new java.awt.Color(255, 255, 255));
        btnProsseguir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnProsseguir.setText("Prosseguir");
        btnProsseguir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProsseguirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProsseguirMouseEntered(evt);
            }
        });
        jPanel4.add(btnProsseguir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 60));

        jpTitulo.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 220, 60));

        jPanel1.add(jpTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 560, 780, 60));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel1.setText("Passo ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 110, 40));

        pnpasso01.setBackground(new java.awt.Color(48, 59, 70));
        pnpasso01.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblpasso01.setForeground(new java.awt.Color(255, 255, 255));
        lblpasso01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblpasso01.setText("2");
        pnpasso01.add(lblpasso01, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 25, 25));

        jPanel1.add(pnpasso01, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, 25, 25));

        pnpasso02.setBackground(new java.awt.Color(109, 127, 145));
        pnpasso02.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblpasso02.setBackground(new java.awt.Color(109, 127, 145));
        lblpasso02.setForeground(new java.awt.Color(255, 255, 255));
        lblpasso02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblpasso02.setText("1");
        pnpasso02.add(lblpasso02, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 25, 25));

        jPanel1.add(pnpasso02, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 25, 25));

        pnpasso03.setBackground(new java.awt.Color(109, 127, 145));
        pnpasso03.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblpasso03.setForeground(new java.awt.Color(255, 255, 255));
        lblpasso03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblpasso03.setText("3");
        pnpasso03.add(lblpasso03, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 25, 25));

        jPanel1.add(pnpasso03, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, 25, 25));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, -1, -1));

        lblDatanasc.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblDatanasc.setForeground(new java.awt.Color(109, 127, 145));
        lblDatanasc.setText("Sinópse");
        jPanel1.add(lblDatanasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 130, -1));

        jpTitulo1.setBackground(new java.awt.Color(109, 127, 145));
        jpTitulo1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloForm4.setBackground(new java.awt.Color(109, 127, 145));
        lblTituloForm4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblTituloForm4.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloForm4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloForm4.setText("FORMULARIO DO FILME");
        jpTitulo1.add(lblTituloForm4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 60));

        jPanel1.add(jpTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 780, 60));

        lblDiretor.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblDiretor.setForeground(new java.awt.Color(109, 127, 145));
        lblDiretor.setText("Número de cópias");
        jPanel1.add(lblDiretor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 110, 20));

        lblSobrenome.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblSobrenome.setForeground(new java.awt.Color(109, 127, 145));
        lblSobrenome.setText("Duração");
        jPanel1.add(lblSobrenome, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 220, 80, 20));

        campoMensagem.setBackground(new java.awt.Color(255, 204, 204));
        campoMensagem.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMensagem.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblMensagem.setForeground(new java.awt.Color(255, 51, 51));
        lblMensagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMensagem.setText("You have an error in you form");
        campoMensagem.add(lblMensagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 5, 750, 30));

        jPanel1.add(campoMensagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 780, 40));

        txtClassEtaria.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtClassEtaria.setForeground(new java.awt.Color(109, 127, 145));
        txtClassEtaria.setToolTipText("Nome");
        txtClassEtaria.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtClassEtariaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtClassEtariaFocusLost(evt);
            }
        });
        txtClassEtaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClassEtariaActionPerformed(evt);
            }
        });
        txtClassEtaria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtClassEtariaKeyReleased(evt);
            }
        });
        jPanel1.add(txtClassEtaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 800, 40));

        lblStatus.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(109, 127, 145));
        lblStatus.setText("Classificação Etária");
        jPanel1.add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, -1, 20));

        intCopias.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        intCopias.setForeground(new java.awt.Color(109, 127, 145));
        intCopias.setToolTipText("Nome");
        intCopias.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                intCopiasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                intCopiasFocusLost(evt);
            }
        });
        intCopias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intCopiasActionPerformed(evt);
            }
        });
        intCopias.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                intCopiasKeyReleased(evt);
            }
        });
        jPanel1.add(intCopias, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 380, 40));

        txtDuracao.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtDuracao.setForeground(new java.awt.Color(109, 127, 145));
        txtDuracao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDuracaoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDuracaoFocusLost(evt);
            }
        });
        txtDuracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDuracaoActionPerformed(evt);
            }
        });
        jPanel1.add(txtDuracao, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 240, 380, 40));

        jTextSinopse.setColumns(20);
        jTextSinopse.setRows(5);
        jScrollPane1.setViewportView(jTextSinopse);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 800, 130));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtClassEtariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClassEtariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClassEtariaActionPerformed

    private void btnProsseguirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProsseguirMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProsseguirMouseEntered

    private void btnProsseguirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProsseguirMouseClicked
        // TODO add your handling code here:

        mensagem = "";
        lblMensagem.setVisible(false);
        campoMensagem.setVisible(false);
        long anoAtualMenosDezAnos = new Date().getTime() - 315576000000L;

        if (txtClassEtaria.getText().trim().equals("Nome") || txtClassEtaria.getText().trim().isEmpty()) {

            mensagem = "Nome não pode ser vazio";
            mensagemSucesso = false;
            txtClassEtaria.grabFocus();
           
            
        } else if (txtSinopse.getText().trim().equals("Sobrenome") || txtSinopse.getText().trim().isEmpty()) {

            mensagem = "Sobrenome não pode ser vazio";
            mensagemSucesso = false;
            txtSinopse.grabFocus();
            
        } else if (!rbtnFeminino.isSelected() && !rbtnMasculino.isSelected()) {

            mensagem = "Sexo deve ser selecionado";
            mensagemSucesso = false;
            rbtnMasculino.grabFocus();
            
        } else if (dtlancamento.getDate() == null) {

            mensagem = "Data de Nascimento não deve ser vazia";
            mensagemSucesso = false;
            dtlancamento.grabFocus();

        } else if (dtlancamento.getDate().getTime() >= anoAtualMenosDezAnos) {

            mensagem = "O cliente deve ter mais de 10 anos";
            mensagemSucesso = false;
            dtlancamento.grabFocus();
            
        } else {
            mensagem = "";
            lblMensagem.setVisible(false);
            campoMensagem.setVisible(false);

            mensagemSucesso = true;

        }

      
        if (mensagemSucesso) {

            clientePasso2 = new FormClientePasso2(this.telaPai);
            this.telaPai.Internal(clientePasso2);

        } else {

            campoMensagem.setBackground(new Color(255, 204, 204));
            campoMensagem.setVisible(true);
            lblMensagem.setText(mensagem);
            lblMensagem.setVisible(true);
        }

    }//GEN-LAST:event_btnProsseguirMouseClicked

    private void txtClassEtariaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClassEtariaKeyReleased
        // TODO add your handling code here:


    }//GEN-LAST:event_txtClassEtariaKeyReleased

    private void txtClassEtariaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtClassEtariaFocusGained
        // TODO add your handling code here:
        if (txtClassEtaria.getText().equals("Nome")) {
            txtClassEtaria.setText("");
            lblDiretor.setVisible(true);
        }
    }//GEN-LAST:event_txtClassEtariaFocusGained

    private void txtClassEtariaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtClassEtariaFocusLost
        // TODO add your handling code here:

        if (txtClassEtaria.getText().isEmpty()) {
            txtClassEtaria.setText("Nome");
            lblDiretor.setVisible(false);
        }
    }//GEN-LAST:event_txtClassEtariaFocusLost

    private void btncancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncancelarMouseClicked
        // TODO add your handling code here:
        
          dispose();

        home = new FormHome();
        this.telaPai.Internal(home);
    }//GEN-LAST:event_btncancelarMouseClicked

    private void intCopiasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_intCopiasFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_intCopiasFocusGained

    private void intCopiasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_intCopiasFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_intCopiasFocusLost

    private void intCopiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intCopiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_intCopiasActionPerformed

    private void intCopiasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_intCopiasKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_intCopiasKeyReleased

    private void txtDuracaoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDuracaoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDuracaoFocusGained

    private void txtDuracaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDuracaoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDuracaoFocusLost

    private void txtDuracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDuracaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDuracaoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnProsseguir;
    private javax.swing.JLabel btncancelar;
    private javax.swing.JPanel campoMensagem;
    private javax.swing.ButtonGroup grpSexo;
    private javax.swing.JTextField intCopias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextSinopse;
    private javax.swing.JPanel jpTitulo;
    private javax.swing.JPanel jpTitulo1;
    private java.awt.Label lblDatanasc;
    private java.awt.Label lblDiretor;
    private javax.swing.JLabel lblMensagem;
    private java.awt.Label lblSobrenome;
    private java.awt.Label lblStatus;
    private javax.swing.JLabel lblTituloForm4;
    private javax.swing.JLabel lblpasso01;
    private javax.swing.JLabel lblpasso02;
    private javax.swing.JLabel lblpasso03;
    private javax.swing.JPanel pnpasso01;
    private javax.swing.JPanel pnpasso02;
    private javax.swing.JPanel pnpasso03;
    private javax.swing.JTextField txtClassEtaria;
    private javax.swing.JTextField txtDuracao;
    // End of variables declaration//GEN-END:variables
}
