/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Validacoes;
import java.awt.Color;
import java.awt.Dimension;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author John Victor
 */
public class FormAdministradorPasso2 extends javax.swing.JInternalFrame {

    boolean mensagemSucesso = false;
    boolean stateemail = false;
    boolean stateCPF = false;
    String mensagem = "";

    private String email;

    FormMenu telaPai = null;

    /**
     * Creates new form Home
     */
    public FormAdministradorPasso2(FormMenu telaPai) {
        initComponents();

        this.telaPai = telaPai;

        txtemail.setText("Email");
        lblemail.setVisible(false);
        lblcpf.setVisible(true);
        lblRG.setVisible(true);
        lblTelefone.setVisible(true);
        campoMensagem.setVisible(false);
        lblMensagem.setVisible(false);
    }

    public void validaCPF(String cpf) {

        try {
            Validacoes v = new Validacoes();

            cpf = cpf.replace(".", "");
            cpf = cpf.replace("-", "");

            //
            if (cpf.equals("11111111111") || cpf.equals("22222222222") || cpf.equals("33333333333")
                    || cpf.equals("44444444444") || cpf.equals("55555555555") || cpf.equals("66666666666")
                    || cpf.equals("77777777777") || cpf.equals("88888888888") || cpf.equals("99999999999")) {

                stateCPF = false;

            } else if ((v.isValidCPF(cpf)) == false) {

                stateCPF = false;

            } else if ((v.isValidCPF(cpf)) == true) {

                stateCPF = true;
            }

        } catch (Exception exp) {

        }

    }

    public void validaEmail(String emaildig) {
        try {
            int pos = emaildig.indexOf("@");
            //Substring iniciando em 0 at� posi��o do caracter especial

            String parte1 = (emaildig.substring(0, pos));
            parte1 = parte1.replace(".", "");
            parte1 = parte1.replace("_", "");
            parte1 = parte1.replace("/", "");
            parte1 = parte1.replace("-", "");
            String parte2 = (emaildig.substring(pos, emaildig.length()));
            email = parte1 + parte2;
            if (!(Pattern.matches("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$", email))) {
                stateemail = false;
            } else {
                stateemail = true;

            }
        } catch (Exception e) {
            stateemail = false;
        }
        //Posi��o do caracter na string

    }

    FormAdministradorPasso3 administradorPasso3;
    FormHome home;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpTitulo = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btncancelar = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnProsseguir = new javax.swing.JLabel();
        pnpasso01 = new javax.swing.JPanel();
        lblpasso01 = new javax.swing.JLabel();
        pnpasso02 = new javax.swing.JPanel();
        lblpasso02 = new javax.swing.JLabel();
        pnpasso03 = new javax.swing.JPanel();
        lblpasso03 = new javax.swing.JLabel();
        pnpasso3 = new javax.swing.JPanel();
        lblpasso3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        lblTituloForm2 = new javax.swing.JLabel();
        txttelefone = new javax.swing.JFormattedTextField();
        txtcpf = new javax.swing.JFormattedTextField();
        txtrg = new javax.swing.JFormattedTextField();
        lblemail = new java.awt.Label();
        lblcpf = new java.awt.Label();
        lblRG = new java.awt.Label();
        lblTelefone = new java.awt.Label();
        campoMensagem = new javax.swing.JPanel();
        lblMensagem = new javax.swing.JLabel();
        jpTitulo1 = new javax.swing.JPanel();
        lblTituloForm4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        setMinimumSize(new java.awt.Dimension(300, 80));
        setPreferredSize(new java.awt.Dimension(1210, 640));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpTitulo.setBackground(new java.awt.Color(255, 255, 255));
        jpTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btncancelar.setBackground(new java.awt.Color(109, 127, 145));
        btncancelar.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btncancelar.setForeground(new java.awt.Color(255, 255, 255));
        btncancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btncancelar.setText("CANCELAR");
        btncancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncancelarMouseClicked(evt);
            }
        });
        jPanel3.add(btncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 60));

        jpTitulo.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 60));

        jPanel4.setBackground(new java.awt.Color(109, 127, 145));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnProsseguir.setBackground(new java.awt.Color(109, 127, 145));
        btnProsseguir.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnProsseguir.setForeground(new java.awt.Color(255, 255, 255));
        btnProsseguir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnProsseguir.setText("Prosseguir");
        btnProsseguir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProsseguirMouseClicked(evt);
            }
        });
        jPanel4.add(btnProsseguir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 60));

        jpTitulo.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 220, 60));

        jPanel1.add(jpTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 560, 780, 60));

        pnpasso01.setBackground(new java.awt.Color(109, 127, 145));
        pnpasso01.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblpasso01.setForeground(new java.awt.Color(255, 255, 255));
        lblpasso01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblpasso01.setText("1");
        pnpasso01.add(lblpasso01, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 25, 25));

        jPanel1.add(pnpasso01, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 25, 25));

        pnpasso02.setBackground(new java.awt.Color(48, 59, 70));
        pnpasso02.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblpasso02.setBackground(new java.awt.Color(109, 127, 145));
        lblpasso02.setForeground(new java.awt.Color(255, 255, 255));
        lblpasso02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblpasso02.setText("2");
        pnpasso02.add(lblpasso02, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 25, 25));

        jPanel1.add(pnpasso02, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, 25, 25));

        pnpasso03.setBackground(new java.awt.Color(109, 127, 145));
        pnpasso03.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblpasso03.setForeground(new java.awt.Color(255, 255, 255));
        lblpasso03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblpasso03.setText("3");
        pnpasso03.add(lblpasso03, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 25, 25));

        jPanel1.add(pnpasso03, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, 25, 25));

        pnpasso3.setBackground(new java.awt.Color(109, 127, 145));
        pnpasso3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblpasso3.setBackground(new java.awt.Color(109, 127, 145));
        lblpasso3.setForeground(new java.awt.Color(255, 255, 255));
        lblpasso3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblpasso3.setText("4");
        pnpasso3.add(lblpasso3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 25, 25));

        jPanel1.add(pnpasso3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 110, 25, 25));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, -1, -1));

        txtemail.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtemail.setForeground(new java.awt.Color(109, 127, 145));
        txtemail.setText("Email");
        txtemail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtemailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtemailFocusLost(evt);
            }
        });
        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        jPanel1.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 780, 40));

        lblTituloForm2.setBackground(new java.awt.Color(109, 127, 145));
        lblTituloForm2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblTituloForm2.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloForm2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloForm2.setText("CANCELAR");
        jPanel1.add(lblTituloForm2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 60));

        txttelefone.setForeground(new java.awt.Color(109, 127, 145));
        try {
            txttelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txttelefone.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txttelefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txttelefoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txttelefoneFocusLost(evt);
            }
        });
        txttelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelefoneActionPerformed(evt);
            }
        });
        jPanel1.add(txttelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 780, 40));

        txtcpf.setForeground(new java.awt.Color(109, 127, 145));
        try {
            txtcpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtcpf.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtcpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtcpfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtcpfFocusLost(evt);
            }
        });
        txtcpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcpfActionPerformed(evt);
            }
        });
        jPanel1.add(txtcpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 370, 40));

        txtrg.setForeground(new java.awt.Color(109, 127, 145));
        try {
            txtrg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-###-###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtrg.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtrg.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtrgFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtrgFocusLost(evt);
            }
        });
        txtrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrgActionPerformed(evt);
            }
        });
        jPanel1.add(txtrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 350, 390, 40));

        lblemail.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblemail.setForeground(new java.awt.Color(109, 127, 145));
        lblemail.setText("Email");
        jPanel1.add(lblemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 440, 20));

        lblcpf.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblcpf.setForeground(new java.awt.Color(109, 127, 145));
        lblcpf.setText("CPF");
        jPanel1.add(lblcpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 370, 20));

        lblRG.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblRG.setForeground(new java.awt.Color(109, 127, 145));
        lblRG.setText("RG");
        jPanel1.add(lblRG, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 330, 370, 20));

        lblTelefone.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblTelefone.setForeground(new java.awt.Color(109, 127, 145));
        lblTelefone.setText("Telefone");
        jPanel1.add(lblTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 370, 20));

        campoMensagem.setBackground(new java.awt.Color(255, 204, 204));
        campoMensagem.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMensagem.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblMensagem.setForeground(new java.awt.Color(255, 51, 51));
        lblMensagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMensagem.setText("You have an error in you form");
        campoMensagem.add(lblMensagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 5, 750, 30));

        jPanel1.add(campoMensagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 780, 40));

        jpTitulo1.setBackground(new java.awt.Color(109, 127, 145));
        jpTitulo1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloForm4.setBackground(new java.awt.Color(109, 127, 145));
        lblTituloForm4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblTituloForm4.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloForm4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloForm4.setText("FORMULARIO DO ADMINISTRADOR");
        jpTitulo1.add(lblTituloForm4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 60));

        jPanel1.add(jpTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 780, 60));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel2.setText("Passo ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 110, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1230, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrgActionPerformed

    private void txtrgFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtrgFocusLost
        // TODO add your handling code here:


    }//GEN-LAST:event_txtrgFocusLost

    private void txtrgFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtrgFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_txtrgFocusGained

    private void txtcpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcpfActionPerformed

    private void txtcpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcpfFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_txtcpfFocusLost

    private void txtcpfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcpfFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_txtcpfFocusGained

    private void txttelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelefoneActionPerformed

    private void txttelefoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttelefoneFocusLost
        // TODO add your handling code here:

        if (txttelefone.getText().isEmpty()) {
            txttelefone.setText("Telefone");
            lblTelefone.setVisible(false);
        }
    }//GEN-LAST:event_txttelefoneFocusLost

    private void txttelefoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttelefoneFocusGained
        // TODO add your handling code here:


    }//GEN-LAST:event_txttelefoneFocusGained

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void txtemailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtemailFocusLost
        // TODO add your handling code here:

        if (txtemail.getText().isEmpty()) {
            txtemail.setText("Email");
            lblemail.setVisible(false);
        }
    }//GEN-LAST:event_txtemailFocusLost

    private void txtemailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtemailFocusGained
        // TODO add your handling code here:
        if (txtemail.getText().equals("Email")) {
            txtemail.setText("");
            lblemail.setVisible(true);
        }

    }//GEN-LAST:event_txtemailFocusGained

    private void btnProsseguirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProsseguirMouseClicked
        // TODO add your handling code here:

        campoMensagem.setVisible(false);
        lblMensagem.setVisible(false);
        mensagem = "";

        validaEmail(txtemail.getText());

        validaCPF(txtcpf.getText());

        if (!stateemail) {
            mensagem = " O email digitado é invalido";
            mensagemSucesso = false;
            txtemail.grabFocus();

        } else if (!stateCPF) {

            mensagem = "O CPF digitado é Invalido";
            mensagemSucesso = false;
            txtcpf.grabFocus();

        } else if (txtrg.getText().trim().isEmpty() || txtrg.getText().equals("  -   -   - ")) {

            mensagem = "RG não pode ser vazio";
            mensagemSucesso = false;
            txtrg.grabFocus();
        } else if (txttelefone.getText().trim().isEmpty() || txttelefone.getText().equals("(  )       -    ")) {

            mensagem = "Telefone não pode ser vazio";
            mensagemSucesso = false;
            txttelefone.grabFocus();
        } else {
            mensagemSucesso = true;
        }

        if (mensagemSucesso) {

            administradorPasso3 = new FormAdministradorPasso3(this.telaPai);
            this.telaPai.Internal(administradorPasso3);
        } else {

            campoMensagem.setBackground(new Color(255, 204, 204));
            campoMensagem.setVisible(true);
            lblMensagem.setText(mensagem);
            lblMensagem.setVisible(true);
        }

    }//GEN-LAST:event_btnProsseguirMouseClicked

    private void btncancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncancelarMouseClicked
        // TODO add your handling code here:
        dispose();

        home = new FormHome();
        this.telaPai.Internal(home);
    }//GEN-LAST:event_btncancelarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnProsseguir;
    private javax.swing.JLabel btncancelar;
    private javax.swing.JPanel campoMensagem;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jpTitulo;
    private javax.swing.JPanel jpTitulo1;
    private javax.swing.JLabel lblMensagem;
    private java.awt.Label lblRG;
    private java.awt.Label lblTelefone;
    private javax.swing.JLabel lblTituloForm2;
    private javax.swing.JLabel lblTituloForm4;
    private java.awt.Label lblcpf;
    private java.awt.Label lblemail;
    private javax.swing.JLabel lblpasso01;
    private javax.swing.JLabel lblpasso02;
    private javax.swing.JLabel lblpasso03;
    private javax.swing.JLabel lblpasso3;
    private javax.swing.JPanel pnpasso01;
    private javax.swing.JPanel pnpasso02;
    private javax.swing.JPanel pnpasso03;
    private javax.swing.JPanel pnpasso3;
    private javax.swing.JFormattedTextField txtcpf;
    private javax.swing.JTextField txtemail;
    private javax.swing.JFormattedTextField txtrg;
    private javax.swing.JFormattedTextField txttelefone;
    // End of variables declaration//GEN-END:variables
}
