/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Dimension;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author John Victor
 */
public class FormClientePasso2 extends javax.swing.JInternalFrame {
        FormMenu telaPai = null;
    /**
     * Creates new form Home
     */
    public FormClientePasso2(FormMenu telaPai) {
        initComponents();
        this.telaPai = telaPai;
        
       txtemail.setText("Email");
       lblemail.setVisible(false); 
       txtcpf.setText("CPF");
       lblcpf.setVisible(false); 
       txtrg.setText("RG");
       lblRG.setVisible(false); 
       txttelefone.setText("Telefone");
       lblTelefone.setVisible(false); 
    }

FormClientePasso3 clientePasso3; 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpTitulo = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblTituloForm3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblTituloForm = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnpasso01 = new javax.swing.JPanel();
        lblpasso01 = new javax.swing.JLabel();
        pnpasso02 = new javax.swing.JPanel();
        lblpasso02 = new javax.swing.JLabel();
        pnpasso03 = new javax.swing.JPanel();
        lblpasso03 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jpTitulo1 = new javax.swing.JPanel();
        lblTituloForm1 = new javax.swing.JLabel();
        lblTituloForm2 = new javax.swing.JLabel();
        txttelefone = new javax.swing.JFormattedTextField();
        txtcpf = new javax.swing.JFormattedTextField();
        txtrg = new javax.swing.JFormattedTextField();
        lblemail = new java.awt.Label();
        lblcpf = new java.awt.Label();
        lblRG = new java.awt.Label();
        lblTelefone = new java.awt.Label();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        setMinimumSize(new java.awt.Dimension(300, 80));
        setPreferredSize(new java.awt.Dimension(1210, 640));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpTitulo.setBackground(new java.awt.Color(255, 255, 255));
        jpTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloForm3.setBackground(new java.awt.Color(109, 127, 145));
        lblTituloForm3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblTituloForm3.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloForm3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloForm3.setText("CANCELAR");
        jPanel3.add(lblTituloForm3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 60));

        jpTitulo.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 60));

        jPanel4.setBackground(new java.awt.Color(109, 127, 145));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloForm.setBackground(new java.awt.Color(109, 127, 145));
        lblTituloForm.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblTituloForm.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloForm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloForm.setText("Prosseguir");
        lblTituloForm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTituloFormMouseClicked(evt);
            }
        });
        jPanel4.add(lblTituloForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 60));

        jpTitulo.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 220, 60));

        jPanel1.add(jpTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 560, 780, 60));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel1.setText("Passo ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 110, 40));

        pnpasso01.setBackground(new java.awt.Color(109, 127, 145));
        pnpasso01.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblpasso01.setForeground(new java.awt.Color(255, 255, 255));
        lblpasso01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblpasso01.setText("1");
        pnpasso01.add(lblpasso01, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 25, 25));

        jPanel1.add(pnpasso01, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 25, 25));

        pnpasso02.setBackground(new java.awt.Color(48, 59, 70));
        pnpasso02.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblpasso02.setBackground(new java.awt.Color(109, 127, 145));
        lblpasso02.setForeground(new java.awt.Color(255, 255, 255));
        lblpasso02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblpasso02.setText("2");
        pnpasso02.add(lblpasso02, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 25, 25));

        jPanel1.add(pnpasso02, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, 25, 25));

        pnpasso03.setBackground(new java.awt.Color(109, 127, 145));
        pnpasso03.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblpasso03.setForeground(new java.awt.Color(255, 255, 255));
        lblpasso03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblpasso03.setText("3");
        pnpasso03.add(lblpasso03, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 25, 25));

        jPanel1.add(pnpasso03, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, 25, 25));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, -1, -1));

        txtemail.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtemail.setForeground(new java.awt.Color(109, 127, 145));
        txtemail.setText("Email");
        txtemail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtemailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtemailFocusLost(evt);
            }
        });
        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        jPanel1.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 780, 40));

        jpTitulo1.setBackground(new java.awt.Color(109, 127, 145));
        jpTitulo1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloForm1.setBackground(new java.awt.Color(109, 127, 145));
        lblTituloForm1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblTituloForm1.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloForm1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloForm1.setText("FORMULARIO DO CLIENTE");
        jpTitulo1.add(lblTituloForm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 60));

        jPanel1.add(jpTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 780, 60));

        lblTituloForm2.setBackground(new java.awt.Color(109, 127, 145));
        lblTituloForm2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblTituloForm2.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloForm2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloForm2.setText("CANCELAR");
        jPanel1.add(lblTituloForm2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 60));

        txttelefone.setForeground(new java.awt.Color(109, 127, 145));
        txttelefone.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txttelefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txttelefoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txttelefoneFocusLost(evt);
            }
        });
        txttelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelefoneActionPerformed(evt);
            }
        });
        jPanel1.add(txttelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 780, 40));

        txtcpf.setForeground(new java.awt.Color(109, 127, 145));
        txtcpf.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtcpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtcpfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtcpfFocusLost(evt);
            }
        });
        txtcpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcpfActionPerformed(evt);
            }
        });
        jPanel1.add(txtcpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 370, 40));

        txtrg.setForeground(new java.awt.Color(109, 127, 145));
        txtrg.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtrg.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtrgFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtrgFocusLost(evt);
            }
        });
        txtrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrgActionPerformed(evt);
            }
        });
        jPanel1.add(txtrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 350, 390, 40));

        lblemail.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblemail.setForeground(new java.awt.Color(109, 127, 145));
        lblemail.setText("Email");
        jPanel1.add(lblemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 440, 20));

        lblcpf.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblcpf.setForeground(new java.awt.Color(109, 127, 145));
        lblcpf.setText("CPF");
        jPanel1.add(lblcpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 370, 20));

        lblRG.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblRG.setForeground(new java.awt.Color(109, 127, 145));
        lblRG.setText("RG");
        jPanel1.add(lblRG, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 330, 370, 20));
        lblRG.getAccessibleContext().setAccessibleName("RG");

        lblTelefone.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblTelefone.setForeground(new java.awt.Color(109, 127, 145));
        lblTelefone.setText("Telefone");
        jPanel1.add(lblTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 370, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1230, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void txttelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelefoneActionPerformed

    private void txtcpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcpfActionPerformed

    private void txtrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrgActionPerformed

    private void txtemailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtemailFocusGained
        // TODO add your handling code here:
         if (txtemail.getText().equals("Email")) {
            txtemail.setText("");
            lblemail.setVisible(true);
        }
        
    }//GEN-LAST:event_txtemailFocusGained

    private void txtemailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtemailFocusLost
        // TODO add your handling code here:
        
         if (txtemail.getText().isEmpty()) {
            txtemail.setText("Email");
            lblemail.setVisible(false);
        }
    }//GEN-LAST:event_txtemailFocusLost

    private void txtcpfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcpfFocusGained
        // TODO add your handling code here:
          if (txtcpf.getText().equals("CPF")) {
            txtcpf.setText("");
            lblcpf.setVisible(true);
        }
        
    }//GEN-LAST:event_txtcpfFocusGained

    private void txtcpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcpfFocusLost
        // TODO add your handling code here:
        
           if (txtcpf.getText().isEmpty()) {
            txtcpf.setText("CPF");
            lblcpf.setVisible(false);
        }
    }//GEN-LAST:event_txtcpfFocusLost

    private void txtrgFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtrgFocusGained
        // TODO add your handling code here:
        if (txtrg.getText().equals("RG")) {
            txtrg.setText("");
            lblRG.setVisible(true);
        }
        
    }//GEN-LAST:event_txtrgFocusGained

    private void txtrgFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtrgFocusLost
        // TODO add your handling code here:
        
          if (txtrg.getText().isEmpty()) {
            txtrg.setText("RG");
            lblRG.setVisible(false);
        }
    }//GEN-LAST:event_txtrgFocusLost

    private void txttelefoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttelefoneFocusGained
        // TODO add your handling code here:
           if (txttelefone.getText().equals("Telefone")) {
            txttelefone.setText("");
            lblTelefone.setVisible(true);
        }
        
        
    }//GEN-LAST:event_txttelefoneFocusGained

    private void txttelefoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttelefoneFocusLost
        // TODO add your handling code here:
        
          if (txttelefone.getText().isEmpty()) {
            txttelefone.setText("Telefone");
            lblTelefone.setVisible(false);
        }
    }//GEN-LAST:event_txttelefoneFocusLost

    private void lblTituloFormMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTituloFormMouseClicked
        // TODO add your handling code here:
        
         clientePasso3 = new FormClientePasso3();
        this.telaPai.Internal(clientePasso3);
    }//GEN-LAST:event_lblTituloFormMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jpTitulo;
    private javax.swing.JPanel jpTitulo1;
    private java.awt.Label lblRG;
    private java.awt.Label lblTelefone;
    private javax.swing.JLabel lblTituloForm;
    private javax.swing.JLabel lblTituloForm1;
    private javax.swing.JLabel lblTituloForm2;
    private javax.swing.JLabel lblTituloForm3;
    private java.awt.Label lblcpf;
    private java.awt.Label lblemail;
    private javax.swing.JLabel lblpasso01;
    private javax.swing.JLabel lblpasso02;
    private javax.swing.JLabel lblpasso03;
    private javax.swing.JPanel pnpasso01;
    private javax.swing.JPanel pnpasso02;
    private javax.swing.JPanel pnpasso03;
    private javax.swing.JFormattedTextField txtcpf;
    private javax.swing.JTextField txtemail;
    private javax.swing.JFormattedTextField txtrg;
    private javax.swing.JFormattedTextField txttelefone;
    // End of variables declaration//GEN-END:variables
}
