/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.WebServiceCep;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author John Victor
 */
public class FormAdministradorPasso4 extends javax.swing.JInternalFrame {

    boolean mensagemSucesso = false;
    String mensagem = "";
    private String cep;

    FormMenu telaPai = null;

    /**
     * Creates new form Home
     */
    public FormAdministradorPasso4(FormMenu telaPai) {

        initComponents();

        txtLogin.setText("Login");
        lblLogin.setVisible(false);
        lblsenha.setVisible(true);
        lblconfirmasenha.setVisible(true);

        campoMensagem.setVisible(false);
        lblMensagem.setVisible(false);

    }

    public void limpar() {

        txtLogin.setText("Login");
        txtsenha.setText("");
        txtconfirmasenha.setText("");

    }

    FormHome home;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnpasso3 = new javax.swing.JPanel();
        lblpasso3 = new javax.swing.JLabel();
        jpTitulo = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btncancelar = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnConfirmar = new javax.swing.JLabel();
        pnpasso01 = new javax.swing.JPanel();
        lblpasso01 = new javax.swing.JLabel();
        pnpasso02 = new javax.swing.JPanel();
        lblpasso02 = new javax.swing.JLabel();
        pnpasso03 = new javax.swing.JPanel();
        lblpasso03 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtLogin = new javax.swing.JFormattedTextField();
        lblLogin = new java.awt.Label();
        lblsenha = new java.awt.Label();
        jpTitulo1 = new javax.swing.JPanel();
        lblTituloForm4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblTituloForm5 = new javax.swing.JLabel();
        campoMensagem = new javax.swing.JPanel();
        lblMensagem = new javax.swing.JLabel();
        lblconfirmasenha = new java.awt.Label();
        txtconfirmasenha = new javax.swing.JPasswordField();
        txtsenha = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(204, 204, 0));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        setMinimumSize(new java.awt.Dimension(300, 80));
        setPreferredSize(new java.awt.Dimension(1210, 640));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnpasso3.setBackground(new java.awt.Color(48, 59, 70));
        pnpasso3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblpasso3.setBackground(new java.awt.Color(109, 127, 145));
        lblpasso3.setForeground(new java.awt.Color(255, 255, 255));
        lblpasso3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblpasso3.setText("4");
        pnpasso3.add(lblpasso3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 25, 25));

        jPanel1.add(pnpasso3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 110, 25, 25));

        jpTitulo.setBackground(new java.awt.Color(255, 255, 255));
        jpTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btncancelar.setBackground(new java.awt.Color(109, 127, 145));
        btncancelar.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btncancelar.setForeground(new java.awt.Color(255, 255, 255));
        btncancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btncancelar.setText("CANCELAR");
        btncancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncancelarMouseClicked(evt);
            }
        });
        jPanel3.add(btncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 60));

        jpTitulo.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 60));

        jPanel4.setBackground(new java.awt.Color(109, 127, 145));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnConfirmar.setBackground(new java.awt.Color(109, 127, 145));
        btnConfirmar.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnConfirmar.setText("CONFIRMAR");
        btnConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfirmarMouseClicked(evt);
            }
        });
        jPanel4.add(btnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 60));

        jpTitulo.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 220, 60));

        jPanel1.add(jpTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 560, 780, 60));

        pnpasso01.setBackground(new java.awt.Color(109, 127, 145));
        pnpasso01.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblpasso01.setForeground(new java.awt.Color(255, 255, 255));
        lblpasso01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblpasso01.setText("1");
        pnpasso01.add(lblpasso01, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 25, 25));

        jPanel1.add(pnpasso01, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 25, 25));

        pnpasso02.setBackground(new java.awt.Color(109, 127, 145));
        pnpasso02.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblpasso02.setBackground(new java.awt.Color(109, 127, 145));
        lblpasso02.setForeground(new java.awt.Color(255, 255, 255));
        lblpasso02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblpasso02.setText("2");
        pnpasso02.add(lblpasso02, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 25, 25));

        jPanel1.add(pnpasso02, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, 25, 25));

        pnpasso03.setBackground(new java.awt.Color(109, 127, 145));
        pnpasso03.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblpasso03.setForeground(new java.awt.Color(255, 255, 255));
        lblpasso03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblpasso03.setText("3");
        pnpasso03.add(lblpasso03, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 25, 25));

        jPanel1.add(pnpasso03, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, 25, 25));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, -1, -1));

        txtLogin.setForeground(new java.awt.Color(109, 127, 145));
        txtLogin.setText("Login");
        txtLogin.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLoginFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLoginFocusLost(evt);
            }
        });
        txtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginActionPerformed(evt);
            }
        });
        jPanel1.add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 780, 40));

        lblLogin.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(109, 127, 145));
        lblLogin.setText("Login");
        jPanel1.add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 40, 20));

        lblsenha.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblsenha.setForeground(new java.awt.Color(109, 127, 145));
        lblsenha.setText("Nova Senha");
        jPanel1.add(lblsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 90, 20));

        jpTitulo1.setBackground(new java.awt.Color(109, 127, 145));
        jpTitulo1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloForm4.setBackground(new java.awt.Color(109, 127, 145));
        lblTituloForm4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblTituloForm4.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloForm4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloForm4.setText("FORMULARIO DO ADMINISTRADOR");
        jpTitulo1.add(lblTituloForm4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 60));

        jPanel1.add(jpTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 780, 60));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel2.setText("Passo ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 110, 40));

        lblTituloForm5.setBackground(new java.awt.Color(109, 127, 145));
        lblTituloForm5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblTituloForm5.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloForm5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloForm5.setText("FORMULARIO DO CLIENTE");
        jPanel1.add(lblTituloForm5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 770, 60));

        campoMensagem.setBackground(new java.awt.Color(255, 204, 204));
        campoMensagem.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMensagem.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblMensagem.setForeground(new java.awt.Color(255, 51, 51));
        lblMensagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMensagem.setText("You have an error in you form");
        campoMensagem.add(lblMensagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 5, 750, 30));

        jPanel1.add(campoMensagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 780, 40));

        lblconfirmasenha.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblconfirmasenha.setForeground(new java.awt.Color(109, 127, 145));
        lblconfirmasenha.setText("Confirmação de Nova Senha");
        jPanel1.add(lblconfirmasenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, -1, 20));

        txtconfirmasenha.setForeground(new java.awt.Color(109, 127, 145));
        txtconfirmasenha.setText("**********");
        txtconfirmasenha.setToolTipText("");
        txtconfirmasenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtconfirmasenhaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtconfirmasenhaFocusLost(evt);
            }
        });
        jPanel1.add(txtconfirmasenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 780, 40));

        txtsenha.setForeground(new java.awt.Color(109, 127, 145));
        txtsenha.setText("**********");
        txtsenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtsenhaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtsenhaFocusLost(evt);
            }
        });
        jPanel1.add(txtsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 780, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1230, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginActionPerformed

    private void btnConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmarMouseClicked
        String senha = new String(txtsenha.getPassword());
        String confirmasenha = new String(txtconfirmasenha.getPassword());

        if (txtLogin.getText().equals("Login") || txtLogin.getText().trim().isEmpty()) {
            mensagem = "Login não pode ser vazio";
            mensagemSucesso = false;
            txtLogin.grabFocus();
        } else if (senha.equals("") || senha.equals("**********")) {
            mensagem = "senha não pode ser vazia";
            mensagemSucesso = false;
            txtsenha.grabFocus();
        } else if (confirmasenha.equals("") || confirmasenha.equals("**********")) {
            mensagem = "A confirmação de senha não pode ser vazia";
            mensagemSucesso = false;
            txtconfirmasenha.grabFocus();
        } else if (!senha.equals(confirmasenha)) {
            mensagem = "A senha e a confirmaçao de senha não correspondem";
            mensagemSucesso = false;
            txtsenha.setText("");
            txtconfirmasenha.setText("**********");
            txtsenha.grabFocus();

        } else {
            mensagemSucesso = true;
        }
        if (mensagemSucesso) {

            JOptionPane.showMessageDialog(null, "vai malandra");

        } else {

            campoMensagem.setBackground(new Color(255, 204, 204));
            campoMensagem.setVisible(true);
            lblMensagem.setText(mensagem);
            lblMensagem.setVisible(true);
            lblMensagem.setForeground(new Color(204, 0, 0));
        }
    }//GEN-LAST:event_btnConfirmarMouseClicked

    private void txtLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLoginFocusGained
        // TODO add your handling code here:

        if (txtLogin.getText().equals("Login")) {
            txtLogin.setText("");
            lblLogin.setVisible(true);
        }

    }//GEN-LAST:event_txtLoginFocusGained

    private void txtLoginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLoginFocusLost
        // TODO add your handling code here:
        if (txtLogin.getText().isEmpty()) {
            txtLogin.setText("Login");
            lblLogin.setVisible(false);
        }

    }//GEN-LAST:event_txtLoginFocusLost

    private void txtsenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtsenhaFocusGained
        // TODO add your handling code here:

        String senha = new String(txtsenha.getPassword());

        if (senha.equals("**********")) {
            txtsenha.setText("");
        }

    }//GEN-LAST:event_txtsenhaFocusGained

    private void txtsenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtsenhaFocusLost
        // TODO add your handling code here:
        String senha = new String(txtsenha.getPassword());
        if (senha.equals("")) {
            txtsenha.setText("**********");
        }
    }//GEN-LAST:event_txtsenhaFocusLost

    private void txtconfirmasenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtconfirmasenhaFocusGained
        // TODO add your handling code here:
        String confirmasenha = new String(txtconfirmasenha.getPassword());

        if (confirmasenha.equals("**********")) {
            txtconfirmasenha.setText("");
        }

    }//GEN-LAST:event_txtconfirmasenhaFocusGained

    private void txtconfirmasenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtconfirmasenhaFocusLost
        // TODO add your handling code here:
        String confirmasenha = new String(txtconfirmasenha.getPassword());

        if (confirmasenha.equals("")) {
            txtconfirmasenha.setText("**********");
        }

    }//GEN-LAST:event_txtconfirmasenhaFocusLost

    private void btncancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncancelarMouseClicked
        // TODO add your handling code here:

        dispose();

        home = new FormHome();
        this.telaPai.Internal(home);
    }//GEN-LAST:event_btncancelarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnConfirmar;
    private javax.swing.JLabel btncancelar;
    private javax.swing.JPanel campoMensagem;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jpTitulo;
    private javax.swing.JPanel jpTitulo1;
    private java.awt.Label lblLogin;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JLabel lblTituloForm4;
    private javax.swing.JLabel lblTituloForm5;
    private java.awt.Label lblconfirmasenha;
    private javax.swing.JLabel lblpasso01;
    private javax.swing.JLabel lblpasso02;
    private javax.swing.JLabel lblpasso03;
    private javax.swing.JLabel lblpasso3;
    private java.awt.Label lblsenha;
    private javax.swing.JPanel pnpasso01;
    private javax.swing.JPanel pnpasso02;
    private javax.swing.JPanel pnpasso03;
    private javax.swing.JPanel pnpasso3;
    private javax.swing.JFormattedTextField txtLogin;
    private javax.swing.JPasswordField txtconfirmasenha;
    private javax.swing.JPasswordField txtsenha;
    // End of variables declaration//GEN-END:variables
}
