/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Dimension;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author John Victor
 */
public class FormClientePasso3 extends javax.swing.JInternalFrame {
    
    /**
     * Creates new form Home
     */
    public FormClientePasso3() {
        initComponents();
        
        
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpTitulo = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblTituloForm3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblTituloForm = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnpasso01 = new javax.swing.JPanel();
        lblpasso01 = new javax.swing.JLabel();
        pnpasso02 = new javax.swing.JPanel();
        lblpasso02 = new javax.swing.JLabel();
        pnpasso03 = new javax.swing.JPanel();
        lblpasso03 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCEP = new javax.swing.JTextField();
        jpTitulo1 = new javax.swing.JPanel();
        lblTituloForm1 = new javax.swing.JLabel();
        lblTituloForm2 = new javax.swing.JLabel();
        txtBairro = new javax.swing.JFormattedTextField();
        txtCidade = new javax.swing.JFormattedTextField();
        cbUF = new javax.swing.JComboBox<>();
        txtRua = new javax.swing.JFormattedTextField();
        txtNumero = new javax.swing.JFormattedTextField();
        lblcidade = new java.awt.Label();
        lblcep = new java.awt.Label();
        lblrua = new java.awt.Label();
        lblnumero = new java.awt.Label();
        lblbairro = new java.awt.Label();
        lbluf = new java.awt.Label();
        jSeparator2 = new javax.swing.JSeparator();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        setMinimumSize(new java.awt.Dimension(300, 80));
        setPreferredSize(new java.awt.Dimension(1210, 640));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpTitulo.setBackground(new java.awt.Color(255, 255, 255));
        jpTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloForm3.setBackground(new java.awt.Color(109, 127, 145));
        lblTituloForm3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblTituloForm3.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloForm3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloForm3.setText("CANCELAR");
        jPanel3.add(lblTituloForm3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 60));

        jpTitulo.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 60));

        jPanel4.setBackground(new java.awt.Color(109, 127, 145));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloForm.setBackground(new java.awt.Color(109, 127, 145));
        lblTituloForm.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblTituloForm.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloForm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloForm.setText("CONFIRMAR");
        lblTituloForm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTituloFormMouseClicked(evt);
            }
        });
        jPanel4.add(lblTituloForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 60));

        jpTitulo.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 220, 60));

        jPanel1.add(jpTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 560, 780, 60));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel1.setText("Passo ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 110, 40));

        pnpasso01.setBackground(new java.awt.Color(109, 127, 145));
        pnpasso01.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblpasso01.setForeground(new java.awt.Color(255, 255, 255));
        lblpasso01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblpasso01.setText("1");
        pnpasso01.add(lblpasso01, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 25, 25));

        jPanel1.add(pnpasso01, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 25, 25));

        pnpasso02.setBackground(new java.awt.Color(109, 127, 145));
        pnpasso02.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblpasso02.setBackground(new java.awt.Color(109, 127, 145));
        lblpasso02.setForeground(new java.awt.Color(255, 255, 255));
        lblpasso02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblpasso02.setText("2");
        pnpasso02.add(lblpasso02, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 25, 25));

        jPanel1.add(pnpasso02, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, 25, 25));

        pnpasso03.setBackground(new java.awt.Color(48, 59, 70));
        pnpasso03.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblpasso03.setForeground(new java.awt.Color(255, 255, 255));
        lblpasso03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblpasso03.setText("3");
        pnpasso03.add(lblpasso03, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 25, 25));

        jPanel1.add(pnpasso03, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, 25, 25));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, -1, -1));

        txtCEP.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtCEP.setForeground(new java.awt.Color(109, 127, 145));
        txtCEP.setText("CEP");
        txtCEP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCEPFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCEPFocusLost(evt);
            }
        });
        txtCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCEPActionPerformed(evt);
            }
        });
        jPanel1.add(txtCEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 780, 40));

        jpTitulo1.setBackground(new java.awt.Color(109, 127, 145));
        jpTitulo1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloForm1.setBackground(new java.awt.Color(109, 127, 145));
        lblTituloForm1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblTituloForm1.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloForm1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloForm1.setText("FORMULARIO DO CLIENTE");
        jpTitulo1.add(lblTituloForm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 60));

        jPanel1.add(jpTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 780, 60));

        lblTituloForm2.setBackground(new java.awt.Color(109, 127, 145));
        lblTituloForm2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblTituloForm2.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloForm2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloForm2.setText("CANCELAR");
        jPanel1.add(lblTituloForm2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 60));

        txtBairro.setForeground(new java.awt.Color(109, 127, 145));
        txtBairro.setText("Bairro");
        txtBairro.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBairroActionPerformed(evt);
            }
        });
        jPanel1.add(txtBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 380, 380, 40));

        txtCidade.setForeground(new java.awt.Color(109, 127, 145));
        txtCidade.setText("Cidade");
        txtCidade.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCidadeActionPerformed(evt);
            }
        });
        jPanel1.add(txtCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 460, 380, 40));

        cbUF.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cbUF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "UF" }));
        jPanel1.add(cbUF, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, 380, 40));

        txtRua.setForeground(new java.awt.Color(109, 127, 145));
        txtRua.setText("Rua");
        txtRua.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtRua.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtRuaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRuaFocusLost(evt);
            }
        });
        txtRua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRuaActionPerformed(evt);
            }
        });
        jPanel1.add(txtRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 780, 40));

        txtNumero.setForeground(new java.awt.Color(109, 127, 145));
        txtNumero.setText("Número");
        txtNumero.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });
        jPanel1.add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 380, 40));

        lblcidade.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblcidade.setForeground(new java.awt.Color(109, 127, 145));
        lblcidade.setText("Cidade");
        jPanel1.add(lblcidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 440, 60, 20));

        lblcep.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblcep.setForeground(new java.awt.Color(109, 127, 145));
        lblcep.setText("CEP");
        jPanel1.add(lblcep, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 40, 20));

        lblrua.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblrua.setForeground(new java.awt.Color(109, 127, 145));
        lblrua.setText("Rua");
        jPanel1.add(lblrua, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 40, 20));

        lblnumero.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblnumero.setForeground(new java.awt.Color(109, 127, 145));
        lblnumero.setText("Número");
        jPanel1.add(lblnumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 50, 20));

        lblbairro.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblbairro.setForeground(new java.awt.Color(109, 127, 145));
        lblbairro.setText("Bairro");
        jPanel1.add(lblbairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 360, 40, 20));

        lbluf.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lbluf.setForeground(new java.awt.Color(109, 127, 145));
        lbluf.setText("UF");
        jPanel1.add(lbluf, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 40, 20));

        jSeparator2.setForeground(new java.awt.Color(109, 127, 145));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, 380, 10));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1230, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCEPActionPerformed

    private void txtBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBairroActionPerformed

    private void txtCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCidadeActionPerformed

    private void txtRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuaActionPerformed

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroActionPerformed

    private void lblTituloFormMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTituloFormMouseClicked
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_lblTituloFormMouseClicked

    private void txtCEPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCEPFocusGained
        // TODO add your handling code here:
        
         if (txtCEP.getText().equals("CEP")) {
            txtCEP.setText("");
            lblcep.setVisible(true);
        }
        
    }//GEN-LAST:event_txtCEPFocusGained

    private void txtCEPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCEPFocusLost
        // TODO add your handling code here:
        
         if (txtCEP.getText().isEmpty()) {
            txtCEP.setText("CEP");
            lblcep.setVisible(false);
        }
    }//GEN-LAST:event_txtCEPFocusLost

    private void txtRuaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRuaFocusGained
        // TODO add your handling code here:
        
           if (txtRua.getText().equals("CEP")) {
            txtRua.setText("");
            lblrua.setVisible(true);
        }
        
    }//GEN-LAST:event_txtRuaFocusGained

    private void txtRuaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRuaFocusLost
        // TODO add your handling code here:
          if (txtRua.getText().isEmpty()) {
            txtRua.setText("CEP");
            lblrua.setVisible(false);
        }
        
    }//GEN-LAST:event_txtRuaFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbUF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel jpTitulo;
    private javax.swing.JPanel jpTitulo1;
    private javax.swing.JLabel lblTituloForm;
    private javax.swing.JLabel lblTituloForm1;
    private javax.swing.JLabel lblTituloForm2;
    private javax.swing.JLabel lblTituloForm3;
    private java.awt.Label lblbairro;
    private java.awt.Label lblcep;
    private java.awt.Label lblcidade;
    private java.awt.Label lblnumero;
    private javax.swing.JLabel lblpasso01;
    private javax.swing.JLabel lblpasso02;
    private javax.swing.JLabel lblpasso03;
    private java.awt.Label lblrua;
    private java.awt.Label lbluf;
    private javax.swing.JPanel pnpasso01;
    private javax.swing.JPanel pnpasso02;
    private javax.swing.JPanel pnpasso03;
    private javax.swing.JFormattedTextField txtBairro;
    private javax.swing.JTextField txtCEP;
    private javax.swing.JFormattedTextField txtCidade;
    private javax.swing.JFormattedTextField txtNumero;
    private javax.swing.JFormattedTextField txtRua;
    // End of variables declaration//GEN-END:variables
}
