/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.WebServiceCep;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author John Victor
 */
public class FormFilmeCategoria extends javax.swing.JInternalFrame {

    boolean mensagemSucesso = false;
    String mensagem = "";
    private String cep;

    
    FormMenu telaPai = null;
    /**
     * Creates new form Home
     */
    public FormFilmeCategoria(FormMenu telaPai) {

        
        this.telaPai = telaPai;
        initComponents();

        campoMensagem.setVisible(false);
        lblMensagem.setVisible(false);

    }



    FormCategoria categoria;
    FormHome home;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpTitulo = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btncancelar = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jpTitulo1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jpTitulo3 = new javax.swing.JPanel();
        lblTituloForm3 = new javax.swing.JLabel();
        lblTituloForm5 = new javax.swing.JLabel();
        btnfilme = new javax.swing.JLabel();
        btncategoria = new javax.swing.JLabel();
        campoMensagem = new javax.swing.JPanel();
        lblMensagem = new javax.swing.JLabel();
        jpTitulo2 = new javax.swing.JPanel();
        lblTituloForm6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 0));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        setMinimumSize(new java.awt.Dimension(300, 80));
        setPreferredSize(new java.awt.Dimension(1210, 640));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpTitulo.setBackground(new java.awt.Color(255, 255, 255));
        jpTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btncancelar.setBackground(new java.awt.Color(109, 127, 145));
        btncancelar.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btncancelar.setForeground(new java.awt.Color(255, 255, 255));
        btncancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btncancelar.setText("CANCELAR");
        btncancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncancelarMouseClicked(evt);
            }
        });
        jPanel3.add(btncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 60));

        jpTitulo.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 220, 60));

        jPanel1.add(jpTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 560, 780, 60));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, -1, -1));

        jpTitulo1.setBackground(new java.awt.Color(144, 161, 181));
        jpTitulo1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/category.png"))); // NOI18N
        jpTitulo1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/film.png"))); // NOI18N
        jpTitulo1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, -1, -1));

        jpTitulo3.setBackground(new java.awt.Color(109, 127, 145));
        jpTitulo3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jpTitulo1.add(jpTitulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 10, 170));

        lblTituloForm3.setBackground(new java.awt.Color(109, 127, 145));
        lblTituloForm3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblTituloForm3.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloForm3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloForm3.setText("FILME");
        jpTitulo1.add(lblTituloForm3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 220, 60));

        lblTituloForm5.setBackground(new java.awt.Color(109, 127, 145));
        lblTituloForm5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblTituloForm5.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloForm5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloForm5.setText("CATEGORIA");
        jpTitulo1.add(lblTituloForm5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 220, 60));
        jpTitulo1.add(btnfilme, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 390, 170));

        btncategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncategoriaMouseClicked(evt);
            }
        });
        jpTitulo1.add(btncategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 170));

        jPanel1.add(jpTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 780, 170));

        campoMensagem.setBackground(new java.awt.Color(255, 204, 204));
        campoMensagem.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMensagem.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblMensagem.setForeground(new java.awt.Color(255, 51, 51));
        lblMensagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMensagem.setText("You have an error in you form");
        campoMensagem.add(lblMensagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 5, 750, 30));

        jPanel1.add(campoMensagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 780, 40));

        jpTitulo2.setBackground(new java.awt.Color(109, 127, 145));
        jpTitulo2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloForm6.setBackground(new java.awt.Color(109, 127, 145));
        lblTituloForm6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblTituloForm6.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloForm6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloForm6.setText("FILME / CATEGORIA");
        jpTitulo2.add(lblTituloForm6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 60));

        jPanel1.add(jpTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 780, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1230, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncategoriaMouseClicked
        // TODO add your handling code here:
          categoria = new FormCategoria(this.telaPai);
            this.telaPai.Internal(categoria);
        
    }//GEN-LAST:event_btncategoriaMouseClicked

    private void btncancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncancelarMouseClicked
        // TODO add your handling code here:
        
          dispose();

        home = new FormHome();
        this.telaPai.Internal(home);
    }//GEN-LAST:event_btncancelarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btncancelar;
    private javax.swing.JLabel btncategoria;
    private javax.swing.JLabel btnfilme;
    private javax.swing.JPanel campoMensagem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jpTitulo;
    private javax.swing.JPanel jpTitulo1;
    private javax.swing.JPanel jpTitulo2;
    private javax.swing.JPanel jpTitulo3;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JLabel lblTituloForm3;
    private javax.swing.JLabel lblTituloForm5;
    private javax.swing.JLabel lblTituloForm6;
    // End of variables declaration//GEN-END:variables
}
